name: Pipeline Java Spring Boot
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Construir com Maven
        run: mvn -B package --file pom.xml -DskipTests

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Executar testes
        run: mvn test

      - name: Executar análise de segurança estática
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: 'credscan,depscan,java'
          src: '.'

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Repositório
        uses: actions/checkout@v2

      - name: Construir imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .

      - name: Fazer login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Enviar imagem para o Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      - name: Enviar notificação para o Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "O Pull Request foi mesclado. A nova imagem Docker foi enviada para o Docker Hub."
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true