name: Pipeline Java Spring Boot
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'  

      - name: Construir com Maven
        run: mvn -B package --file pom.xml -DskipTests  

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'  

      - name: Executar testes
        run: mvn test  

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Hello, Word!'
        if: github.ref == 'refs/heads/main'  
